# For a complete example, review https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config/#full-example
region: us
version: 2
tunnels:
  larcity-accounts:
    proto: http
    addr: 16006
    domain: accounts.larcity.ngrok.dev
