#!/usr/bin/env bash

mongosh --authenticationDatabase admin \
  --username $MONGO_INITDB_ROOT_USERNAME --password $MONGO_INITDB_ROOT_PASSWORD \
  --file /docker-entrypoint-initdb.d/init-doc-stores.js
