name: Frontend test suite

on:
  pull_request:

env:
  CI: true
  RAILS_ENV: test
  PROJECT_ROOT: .

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Check ruby version
        run: ruby -v

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Run bundle install
        working-directory: ${{env.PROJECT_ROOT}}
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Enable corepack
        run: |
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Clobber assets & stylesheets
        run: |
          bundle exec rake dartsass:clobber
          bundle exec rake tailwindcss:clobber
          bundle exec rake assets:clobber

      - name: Build assets - stylesheets
        run: |
          bundle exec rake dartsass:build
          bundle exec rake tailwindcss:build

      - name: Build assets - frontend JS
        run: |
          bundle exec rake vite:build_all

      - name: Install Yarn dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test
